### ISSUE TITLE
Puppet Execs should be avoided

### ISSUE THREAD

**Issue by EmilienM** [redhat-cip/puppet-ovn#1]
Puppet Execs are usually a bad practice, most of the case because they are not correctly idempotent or rely to a CLI that often change.

The best practice is to write Puppet providers.
For example, `ovs-vsctl` command could be added in https://github.com/openstack/puppet-vswitch module.

**Comment by anbu-enovance** [comment]
Hi Emilien,
Thank you for the review. This is here just to incubate it till we are ready to push it to the github.com/openstack. 
Will it be neat if I write a type named 'ovn_remote' and check if it's equal to a particular value inside this project itself?

**Comment by anbu-enovance** [comment]
@EmilienM I had published a patch[1] in puppet-vswitch to include your suggestion. Kindly have a look

[1] - https://review.openstack.org/#/c/285996/

**Comment by EmilienM** [comment]
Thanks to consider that work, let's continue the review on Gerrit.
