### ISSUE TITLE
Puppet Lint is not happy

### ISSUE THREAD

**Issue by EmilienM** [redhat-cip/puppet-ovn#2]
puppet-ovn does not seem to be Lint compliant.

Example:
https://github.com/redhat-cip/puppet-ovn/blob/master/manifests/params.pp
- missing Default case
- Usage of " instead of ' for parameters without variable.
- etc.

**Comment by anbu-enovance** [comment]
This is just experimental. I just wanted to get some opinion before working on the other stuffs.
