### ISSUE TITLE
Question: move this module to OpenStack?

### ISSUE THREAD

**Issue by EmilienM** [redhat-cip/puppet-ovn#4]
It's a bug, not a question. Why not moving this module under OpenStack Infra?
It would be like puppet-ceph or puppet-pacemaker, not under any tent. But it would take benefit of the gate (unit tests, lint, syntax, beaker and integration with TripleO in the future) easily.

**Comment by anbu-enovance** [comment]
Will have to eventually move to the openstack infra.

**Comment by EmilienM** [comment]
Cool, closing the issue if it's in your backlog.
